export const movieDB = [
  {
    Title: "Inception",
    Year: "2010",
    Rated: "PG-13",
    Released: "16 Jul 2010",
    Runtime: "148 min",
    Genre: "Action, Adventure, Sci-Fi, Thriller",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy",
    Plot:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    Language: "English, Japanese, French",
    Country: "USA, UK",
    Awards: "Won 4 Oscars. Another 152 wins & 217 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.8/10" },
      { Source: "Rotten Tomatoes", Value: "87%" },
      { Source: "Metacritic", Value: "74/100" },
    ],
    Metascore: "74",
    imdbRating: "8.8",
    imdbVotes: "2,003,841",
    imdbID: "imdb0000001",
    Type: "movie",
    DVD: "07 Dec 2010",
    BoxOffice: "$292,568,851",
    Production: "Warner Bros. Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Lord of the Rings",
    Year: "1978",
    Rated: "PG",
    Released: "15 Nov 1978",
    Runtime: "132 min",
    Genre: "Animation, Adventure, Fantasy",
    Director: "Ralph Bakshi",
    Writer:
      "Chris Conkling (screenplay), Peter S. Beagle (screenplay), J.R.R. Tolkien (novels)",
    Actors: "Christopher Guard, William Squire, Michael Scholes, John Hurt",
    Plot:
      "The Fellowship of the Ring embark on a journey to destroy the One Ring and end Sauron's reign over Middle-earth.",
    Language: "English, Sindarin",
    Country: "USA, UK, Spain",
    Awards: "Nominated for 1 Golden Globe. Another 1 win & 2 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOGMyNWJhZmYtNGQxYi00Y2ZjLWJmNjktNTgzZWJjOTg4YjM3L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.2/10" },
      { Source: "Rotten Tomatoes", Value: "52%" },
    ],
    Metascore: "N/A",
    imdbRating: "6.2",
    imdbVotes: "29,107",
    imdbID: "imdb0000002",
    Type: "movie",
    DVD: "11 Sep 2001",
    BoxOffice: "N/A",
    Production: "WARNER BROTHERS PICTURES",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Cast Away",
    Year: "2000",
    Rated: "PG-13",
    Released: "22 Dec 2000",
    Runtime: "143 min",
    Genre: "Adventure, Drama, Romance",
    Director: "Robert Zemeckis",
    Writer: "William Broyles Jr.",
    Actors: "Paul Sanchez, Lari White, Leonid Citer, David Allen Brooks",
    Plot:
      "A FedEx executive undergoes a physical and emotional transformation after crash landing on a deserted island.",
    Language: "English, Russian",
    Country: "USA",
    Awards: "Nominated for 2 Oscars. Another 15 wins & 35 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2Y5ZTU4YjctMDRmMC00MTg4LWE1M2MtMjk4MzVmOTE4YjkzXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.8/10" },
      { Source: "Rotten Tomatoes", Value: "88%" },
      { Source: "Metacritic", Value: "73/100" },
    ],
    Metascore: "73",
    imdbRating: "7.8",
    imdbVotes: "509,405",
    imdbID: "imdb0000003",
    Type: "movie",
    DVD: "12 Jun 2001",
    BoxOffice: "N/A",
    Production: "20th Century Fox",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Catch Me If You Can",
    Year: "2002",
    Rated: "PG-13",
    Released: "25 Dec 2002",
    Runtime: "141 min",
    Genre: "Biography, Crime, Drama",
    Director: "Steven Spielberg",
    Writer:
      "Jeff Nathanson (screenplay), Frank Abagnale Jr. (book), Stan Redding (book)",
    Actors: "Leonardo DiCaprio, Tom Hanks, Christopher Walken, Martin Sheen",
    Plot:
      "A seasoned FBI agent pursues Frank Abagnale Jr. who, before his 19th birthday, successfully forged millions of dollars' worth of checks while posing as a Pan Am pilot, a doctor, and a legal prosecutor.",
    Language: "English, French",
    Country: "USA, Canada",
    Awards: "Nominated for 2 Oscars. Another 16 wins & 44 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.1/10" },
      { Source: "Rotten Tomatoes", Value: "96%" },
      { Source: "Metacritic", Value: "75/100" },
    ],
    Metascore: "75",
    imdbRating: "8.1",
    imdbVotes: "796,533",
    imdbID: "imdb0000004",
    Type: "movie",
    DVD: "06 May 2003",
    BoxOffice: "$164,400,000",
    Production: "DreamWorks SKG",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Terminal",
    Year: "2004",
    Rated: "PG-13",
    Released: "18 Jun 2004",
    Runtime: "128 min",
    Genre: "Comedy, Drama, Romance",
    Director: "Steven Spielberg",
    Writer:
      "Andrew Niccol (story), Sacha Gervasi (story), Sacha Gervasi (screenplay), Jeff Nathanson (screenplay)",
    Actors: "Tom Hanks, Catherine Zeta-Jones, Stanley Tucci, Chi McBride",
    Plot:
      "An Eastern European tourist unexpectedly finds himself stranded in JFK airport, and must take up temporary residence there.",
    Language: "English, Bulgarian, Spanish, Russian, Mandarin, German, French",
    Country: "USA",
    Awards: "7 wins & 8 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTM1MTIwNTMxOF5BMl5BanBnXkFtZTcwNjIxMjQyMw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.4/10" },
      { Source: "Rotten Tomatoes", Value: "61%" },
      { Source: "Metacritic", Value: "55/100" },
    ],
    Metascore: "55",
    imdbRating: "7.4",
    imdbVotes: "396,124",
    imdbID: "imdb0000005",
    Type: "movie",
    DVD: "23 Nov 2004",
    BoxOffice: "$77,032,279",
    Production: "DreamWorks SKG",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Titanic",
    Year: "1997",
    Rated: "PG-13",
    Released: "19 Dec 1997",
    Runtime: "194 min",
    Genre: "Drama, Romance",
    Director: "James Cameron",
    Writer: "James Cameron",
    Actors: "Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates",
    Plot:
      "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    Language: "English, Swedish, Italian, French",
    Country: "USA, Mexico, Australia, Canada",
    Awards: "Won 11 Oscars. Another 113 wins & 83 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.8/10" },
      { Source: "Rotten Tomatoes", Value: "89%" },
      { Source: "Metacritic", Value: "75/100" },
    ],
    Metascore: "75",
    imdbRating: "7.8",
    imdbVotes: "1,022,060",
    imdbID: "imdb0000006",
    Type: "movie",
    DVD: "10 Sep 2012",
    BoxOffice: "N/A",
    Production: "Paramount Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Avengers",
    Year: "2012",
    Rated: "PG-13",
    Released: "04 May 2012",
    Runtime: "143 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Joss Whedon",
    Writer: "Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)",
    Actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
    Plot:
      "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    Language: "English, Russian, Hindi",
    Country: "USA",
    Awards: "Nominated for 1 Oscar. Another 38 wins & 79 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.0/10" },
      { Source: "Rotten Tomatoes", Value: "92%" },
      { Source: "Metacritic", Value: "69/100" },
    ],
    Metascore: "69",
    imdbRating: "8.0",
    imdbVotes: "1,239,566",
    imdbID: "imdb0000007",
    Type: "movie",
    DVD: "25 Sep 2012",
    BoxOffice: "$623,279,547",
    Production: "Walt Disney Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Star Wars: Episode IV - A New Hope",
    Year: "1977",
    Rated: "PG",
    Released: "25 May 1977",
    Runtime: "121 min",
    Genre: "Action, Adventure, Fantasy, Sci-Fi",
    Director: "George Lucas",
    Writer: "George Lucas",
    Actors: "Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing",
    Plot:
      "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
    Language: "English",
    Country: "USA",
    Awards: "Won 6 Oscars. Another 52 wins & 28 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.6/10" },
      { Source: "Rotten Tomatoes", Value: "92%" },
      { Source: "Metacritic", Value: "90/100" },
    ],
    Metascore: "90",
    imdbRating: "8.6",
    imdbVotes: "1,203,629",
    imdbID: "imdb0000008",
    Type: "movie",
    DVD: "21 Sep 2004",
    BoxOffice: "N/A",
    Production: "20th Century Fox",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Avatar",
    Year: "2009",
    Rated: "PG-13",
    Released: "18 Dec 2009",
    Runtime: "162 min",
    Genre: "Action, Adventure, Fantasy, Sci-Fi",
    Director: "James Cameron",
    Writer: "James Cameron",
    Actors: "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
    Plot:
      "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    Language: "English, Spanish",
    Country: "USA",
    Awards: "Won 3 Oscars. Another 86 wins & 129 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.8/10" },
      { Source: "Rotten Tomatoes", Value: "82%" },
      { Source: "Metacritic", Value: "83/100" },
    ],
    Metascore: "83",
    imdbRating: "7.8",
    imdbVotes: "1,101,100",
    imdbID: "imdb0000009",
    Type: "movie",
    DVD: "22 Apr 2010",
    BoxOffice: "$749,700,000",
    Production: "20th Century Fox",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Gladiator",
    Year: "2000",
    Rated: "R",
    Released: "05 May 2000",
    Runtime: "155 min",
    Genre: "Action, Adventure, Drama",
    Director: "Ridley Scott",
    Writer:
      "David Franzoni (story), David Franzoni (screenplay), John Logan (screenplay), William Nicholson (screenplay)",
    Actors: "Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed",
    Plot:
      "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    Language: "English",
    Country: "USA, UK, Malta, Morocco",
    Awards: "Won 5 Oscars. Another 54 wins & 104 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.5/10" },
      { Source: "Rotten Tomatoes", Value: "77%" },
      { Source: "Metacritic", Value: "67/100" },
    ],
    Metascore: "67",
    imdbRating: "8.5",
    imdbVotes: "1,303,529",
    imdbID: "imdb0000010",
    Type: "movie",
    DVD: "21 Nov 2000",
    BoxOffice: "N/A",
    Production: "Dreamworks Distribution LLC",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Slumdog Millionaire",
    Year: "2008",
    Rated: "R",
    Released: "25 Dec 2008",
    Runtime: "120 min",
    Genre: "Drama, Romance",
    Director: "Danny Boyle, Loveleen Tandan(co-director)",
    Writer: "Simon Beaufoy (screenplay), Vikas Swarup (novel)",
    Actors: "Dev Patel, Saurabh Shukla, Anil Kapoor, Raj Zutshi",
    Plot:
      'A Mumbai teenager reflects on his life after being accused of cheating on the Indian version of "Who Wants to be a Millionaire?".',
    Language: "English, Hindi, French, German",
    Country: "UK, USA",
    Awards: "Won 8 Oscars. Another 147 wins & 131 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZmNjZWI3NzktYWI1Mi00OTAyLWJkNTYtMzUwYTFlZDA0Y2UwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.0/10" },
      { Source: "Rotten Tomatoes", Value: "91%" },
      { Source: "Metacritic", Value: "84/100" },
    ],
    Metascore: "84",
    imdbRating: "8.0",
    imdbVotes: "785,456",
    imdbID: "imdb0000011",
    Type: "movie",
    DVD: "31 Mar 2009",
    BoxOffice: "$141,243,551",
    Production: "Fox Searchlight Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Dark Knight",
    Year: "2008",
    Rated: "PG-13",
    Released: "18 Jul 2008",
    Runtime: "152 min",
    Genre: "Action, Crime, Drama, Thriller",
    Director: "Christopher Nolan",
    Writer:
      "Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)",
    Actors: "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
    Plot:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Language: "English, Mandarin",
    Country: "USA, UK",
    Awards: "Won 2 Oscars. Another 153 wins & 159 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.0/10" },
      { Source: "Rotten Tomatoes", Value: "94%" },
      { Source: "Metacritic", Value: "84/100" },
    ],
    Metascore: "84",
    imdbRating: "9.0",
    imdbVotes: "2,234,169",
    imdbID: "imdb0000012",
    Type: "movie",
    DVD: "09 Dec 2008",
    BoxOffice: "$533,316,061",
    Production: "Warner Bros. Pictures/Legendary",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Joker",
    Year: "2019",
    Rated: "R",
    Released: "04 Oct 2019",
    Runtime: "122 min",
    Genre: "Crime, Drama, Thriller",
    Director: "Todd Phillips",
    Writer:
      "Todd Phillips, Scott Silver, Bob Kane (based on characters created by), Bill Finger (based on characters created by), Jerry Robinson (based on characters created by)",
    Actors: "Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy",
    Plot:
      "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
    Language: "English",
    Country: "USA, Canada",
    Awards: "Won 2 Oscars. Another 97 wins & 201 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.5/10" },
      { Source: "Rotten Tomatoes", Value: "68%" },
      { Source: "Metacritic", Value: "59/100" },
    ],
    Metascore: "59",
    imdbRating: "8.5",
    imdbVotes: "844,981",
    imdbID: "imdb0000013",
    Type: "movie",
    DVD: "17 Dec 2019",
    BoxOffice: "N/A",
    Production: "Warner Bros. Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Life of Pie",
    Year: "2017",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "N/A",
    Genre: "Drama",
    Director: "N/A",
    Writer: "Jennifer Ortega",
    Actors: "N/A",
    Plot:
      "Violet sells perfume and tries kill herself at work. While recuperating at home, she hallucinates 80's rock icons.. She decides to write a metaphysical book about pie and falls in love with a man she is thinks is a demon.",
    Language: "N/A",
    Country: "USA",
    Awards: "N/A",
    Poster: "https://media.s-bol.com/n5Q9PQOQOzvl/550x775.jpg",
    Ratings: [],
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "N/A",
    imdbID: "imdb0000014",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Rangasthalam 1985",
    Year: "2018",
    Rated: "Not Rated",
    Released: "29 Mar 2018",
    Runtime: "170 min",
    Genre: "Action, Drama",
    Director: "Sukumar",
    Writer:
      "Sukumar (story), Sukumar (screenplay), Srinivas Rongali (dialogue), Buchi Babu Sana (dialogue), Kasi Vishal (dialogue), Thota Srinivas (dialogue), Srinivas Rongali (additional screenplay), Buchi Babu Sana (additional screenplay), Kasi Vishal (additional screenplay)",
    Actors: "Ram Charan, Samantha Ruth Prabhu, Aadhi, Jagapathi Babu",
    Plot:
      "The fear of his elder brother's death starts to haunt an innocent, hearing impaired guy after they both join forces to overthrow the unlawful 30 year long regime of their village's president.",
    Language: "Telugu",
    Country: "India",
    Awards: "12 wins & 10 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjQ1MjFkN2EtOTU4NS00NDkzLThhNzItODkzYWNjZDMxZjE0XkEyXkFqcGdeQXVyNTgxODY5ODI@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.4/10" }],
    Metascore: "N/A",
    imdbRating: "8.4",
    imdbVotes: "17,914",
    imdbID: "imdb0000015",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Dhruva",
    Year: "2016",
    Rated: "Not Rated",
    Released: "09 Dec 2016",
    Runtime: "165 min",
    Genre: "Action, Thriller",
    Director: "Surrender Reddy",
    Writer:
      "Shivgopal Krishna (hindi dialogue), Mohan Raja, Vema Reddy (Writer)",
    Actors: "Ram Charan, Arvind Swamy, Rakul Preet Singh, Olga Andrievskaya",
    Plot:
      "A committed police officer is on a very dangerous mission to destroy the most corrupt person in the country, Siddharth Abhimanyu.",
    Language: "Telugu, Hindi",
    Country: "India",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNmZhNDMyZDQtNjRmNC00OWRhLWI4OGItNmZlMGRiMzk4YTNjXkEyXkFqcGdeQXVyNjIwNDI3NzI@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "7.9/10" }],
    Metascore: "N/A",
    imdbRating: "7.9",
    imdbVotes: "4,824",
    imdbID: "imdb0000016",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Life",
    Year: "2017",
    Rated: "R",
    Released: "24 Mar 2017",
    Runtime: "104 min",
    Genre: "Horror, Sci-Fi, Thriller",
    Director: "Daniel Espinosa",
    Writer: "Rhett Reese, Paul Wernick",
    Actors: "Hiroyuki Sanada, Ryan Reynolds, Rebecca Ferguson, Jake Gyllenhaal",
    Plot:
      "A team of scientists aboard the International Space Station discover a rapidly evolving life form that caused extinction on Mars and now threatens all life on Earth.",
    Language: "English, Japanese, Vietnamese",
    Country: "UK, USA",
    Awards: "7 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMzAwMmQxNTctYjVmYi00MDdlLWEzMWUtOTE5NTRiNDhhNjI2L2ltYWdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.6/10" },
      { Source: "Rotten Tomatoes", Value: "67%" },
      { Source: "Metacritic", Value: "54/100" },
    ],
    Metascore: "54",
    imdbRating: "6.6",
    imdbVotes: "201,092",
    imdbID: "imdb0000017",
    Type: "movie",
    DVD: "20 Jun 2017",
    BoxOffice: "$30,180,466",
    Production: "Skydance Films",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Black Panther",
    Year: "2018",
    Rated: "PG-13",
    Released: "16 Feb 2018",
    Runtime: "134 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Ryan Coogler",
    Writer:
      "Ryan Coogler, Joe Robert Cole, Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel Comics by)",
    Actors: "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Danai Gurira",
    Plot:
      "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
    Language: "English, Swahili, Nama, Xhosa, Korean",
    Country: "USA",
    Awards: "Won 3 Oscars. Another 109 wins & 265 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.3/10" },
      { Source: "Rotten Tomatoes", Value: "96%" },
      { Source: "Metacritic", Value: "88/100" },
    ],
    Metascore: "88",
    imdbRating: "7.3",
    imdbVotes: "591,538",
    imdbID: "imdb0000018",
    Type: "movie",
    DVD: "15 May 2018",
    BoxOffice: "$501,105,037",
    Production: "Marvel Studios",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Black",
    Year: "2005",
    Rated: "Not Rated",
    Released: "04 Feb 2005",
    Runtime: "122 min",
    Genre: "Drama",
    Director: "Sanjay Leela Bhansali",
    Writer:
      "Sanjay Leela Bhansali (screenplay), Bhavani Iyer (English dialogue), Bhavani Iyer (screenplay), Prakash Kapadia (dialogue), Prakash Kapadia (screenplay)",
    Actors: "Amitabh Bachchan, Rani Mukerji, Shernaz Patel, Ayesha Kapoor",
    Plot:
      "The cathartic tale of a young woman who can't see, hear or talk and the teacher who brings a ray of light into her dark world.",
    Language: "Hindi, English",
    Country: "India",
    Awards: "56 wins & 4 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNTI5MmE5M2UtZjIzYS00M2JjLWIwNDItYTY2ZWNiODBmYTBiXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.2/10" },
      { Source: "Rotten Tomatoes", Value: "67%" },
    ],
    Metascore: "N/A",
    imdbRating: "8.2",
    imdbVotes: "32,309",
    imdbID: "imdb0000019",
    Type: "movie",
    DVD: "10 May 2005",
    BoxOffice: "$125,342",
    Production: "Evokative Films",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Race",
    Year: "2016",
    Rated: "PG-13",
    Released: "19 Feb 2016",
    Runtime: "134 min",
    Genre: "Biography, Drama, Sport",
    Director: "Stephen Hopkins",
    Writer: "Joe Shrapnel, Anna Waterhouse",
    Actors: "Stephan James, Jason Sudeikis, Eli Goree, Shanice Banton",
    Plot:
      "Jesse Owens' quest to become the greatest track and field athlete in history thrusts him onto the world stage of the 1936 Olympics, where he faces off against Adolf Hitler's vision of Aryan supremacy.",
    Language: "English, German",
    Country: "Canada, Germany, France",
    Awards: "6 wins & 8 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTQ3MDM1MDU2NF5BMl5BanBnXkFtZTgwMzM3OTIzNzE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.1/10" },
      { Source: "Rotten Tomatoes", Value: "62%" },
      { Source: "Metacritic", Value: "56/100" },
    ],
    Metascore: "56",
    imdbRating: "7.1",
    imdbVotes: "33,909",
    imdbID: "imdb0000020",
    Type: "movie",
    DVD: "31 May 2016",
    BoxOffice: "$14,319,394",
    Production: "Focus Features",
    Website: "N/A",
    Response: "True",
  },
];
