export const movieDB = [
  {
    Title: "Inception",
    Year: "2010",
    Released: "16 Jul 2010",
    Genre: "Action, Adventure, Sci-Fi, Thriller",
    Director: "Christopher Nolan",
    Plot:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    Language: "English, Japanese, French",
    Country: "USA, UK",
    Awards: "Won 4 Oscars. Another 152 wins & 217 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    imdbRating: "8.8",
    imdbID: "imdb0000001",
    Production: "Warner Bros. Pictures",
  },
  {
    Title: "The Lord of the Rings",
    Year: "1978",
    Rated: "PG",
    Released: "15 Nov 1978",
    Runtime: "132 min",
    Genre: "Animation, Adventure, Fantasy",
    Director: "Ralph Bakshi",
    Plot:
      "The Fellowship of the Ring embark on a journey to destroy the One Ring and end Sauron's reign over Middle-earth.",
    Language: "English, Sindarin",
    Country: "USA, UK, Spain",
    Awards: "Nominated for 1 Golden Globe. Another 1 win & 2 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOGMyNWJhZmYtNGQxYi00Y2ZjLWJmNjktNTgzZWJjOTg4YjM3L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    imdbRating: "6.2",

    imdbID: "imdb0000002",
    Production: "WARNER BROTHERS PICTURES",
  },
  {
    Title: "Cast Away",
    Year: "2000",
    Released: "22 Dec 2000",

    Genre: "Adventure, Drama, Romance",
    Director: "Robert Zemeckis",
    Plot:
      "A FedEx executive undergoes a physical and emotional transformation after crash landing on a deserted island.",
    Language: "English, Russian",
    Country: "USA",
    Awards: "Nominated for 2 Oscars. Another 15 wins & 35 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2Y5ZTU4YjctMDRmMC00MTg4LWE1M2MtMjk4MzVmOTE4YjkzXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.8/10" },
      { Source: "Rotten Tomatoes", Value: "88%" },
      { Source: "Metacritic", Value: "73/100" },
    ],
    imdbRating: "7.8",
    imdbID: "imdb0000003",
    Production: "20th Century Fox",
  },
  {
    Title: "Catch Me If You Can",
    Year: "2002",
    Released: "25 Dec 2002",
    Genre: "Biography, Crime, Drama",
    Director: "Steven Spielberg",
    Plot:
      "A seasoned FBI agent pursues Frank Abagnale Jr. who, before his 19th birthday, successfully forged millions of dollars' worth of checks while posing as a Pan Am pilot, a doctor, and a legal prosecutor.",
    Language: "English, French",
    Country: "USA, Canada",
    Awards: "Nominated for 2 Oscars. Another 16 wins & 44 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_SX300.jpg",
    imdbRating: "8.1",
    imdbID: "imdb0000004",
    Production: "DreamWorks SKG",
  },
  {
    Title: "The Terminal",
    Year: "2004",
    Released: "18 Jun 2004",
    Genre: "Comedy, Drama, Romance",
    Director: "Steven Spielberg",
    Plot:
      "An Eastern European tourist unexpectedly finds himself stranded in JFK airport, and must take up temporary residence there.",
    Language: "English, Bulgarian, Spanish, Russian, Mandarin, German, French",
    Country: "USA",
    Awards: "7 wins & 8 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTM1MTIwNTMxOF5BMl5BanBnXkFtZTcwNjIxMjQyMw@@._V1_SX300.jpg",
    imdbRating: "7.4",
    imdbID: "imdb0000005",
    Production: "DreamWorks SKG",
  },
  {
    Title: "Titanic",
    Year: "1997",
    Released: "19 Dec 1997",
    Genre: "Drama, Romance",
    Director: "James Cameron",
    Plot:
      "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    Language: "English, Swedish, Italian, French",
    Country: "USA, Mexico, Australia, Canada",
    Awards: "Won 11 Oscars. Another 113 wins & 83 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    imdbRating: "7.8",
    imdbID: "imdb0000006",
    Production: "Paramount Pictures",
  },
  {
    Title: "The Avengers",
    Year: "2012",
    Released: "04 May 2012",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Joss Whedon",
    Plot:
      "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    Language: "English, Russian, Hindi",
    Country: "USA",
    Awards: "Nominated for 1 Oscar. Another 38 wins & 79 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    imdbRating: "8.0",
    imdbID: "imdb0000007",
    Production: "Walt Disney Pictures",
  },
  {
    Title: "Star Wars: Episode IV - A New Hope",
    Year: "1977",
    Released: "25 May 1977",
    Genre: "Action, Adventure, Fantasy, Sci-Fi",
    Director: "George Lucas",
    Plot:
      "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
    Language: "English",
    Country: "USA",
    Awards: "Won 6 Oscars. Another 52 wins & 28 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    imdbRating: "8.6",
    imdbVotes: "1,203,629",
    imdbID: "imdb0000008",
    Production: "20th Century Fox",
  },
  {
    Title: "Avatar",
    Year: "2009",
    Released: "18 Dec 2009",
    Genre: "Action, Adventure, Fantasy, Sci-Fi",
    Director: "James Cameron",
    Plot:
      "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    Language: "English, Spanish",
    Country: "USA",
    Awards: "Won 3 Oscars. Another 86 wins & 129 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
    imdbRating: "7.8",
    imdbID: "imdb0000009",
    Production: "20th Century Fox",
  },
  {
    Title: "Gladiator",
    Year: "2000",
    Released: "05 May 2000",
    Genre: "Action, Adventure, Drama",
    Director: "Ridley Scott",
    Plot:
      "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    Language: "English",
    Country: "USA, UK, Malta, Morocco",
    Awards: "Won 5 Oscars. Another 54 wins & 104 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    imdbRating: "8.5",
    imdbVotes: "1,303,529",
    imdbID: "imdb0000010",
    Production: "Dreamworks Distribution LLC",
  },
  {
    Title: "Slumdog Millionaire",
    Year: "2008",
    Released: "25 Dec 2008",
    Genre: "Drama, Romance",
    Director: "Danny Boyle, Loveleen Tandan(co-director)",
    Plot:
      'A Mumbai teenager reflects on his life after being accused of cheating on the Indian version of "Who Wants to be a Millionaire?".',
    Language: "English, Hindi, French, German",
    Country: "UK, USA",
    Awards: "Won 8 Oscars. Another 147 wins & 131 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZmNjZWI3NzktYWI1Mi00OTAyLWJkNTYtMzUwYTFlZDA0Y2UwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    imdbRating: "8.0",
    imdbID: "imdb0000011",
    Production: "Fox Searchlight Pictures",
  },
  {
    Title: "The Dark Knight",
    Year: "2008",
    Released: "18 Jul 2008",
    Genre: "Action, Crime, Drama, Thriller",
    Director: "Christopher Nolan",
    Plot:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Language: "English, Mandarin",
    Country: "USA, UK",
    Awards: "Won 2 Oscars. Another 153 wins & 159 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    imdbRating: "9.0",
    imdbID: "imdb0000012",
    Production: "Warner Bros. Pictures/Legendary",
  },
  {
    Title: "Joker",
    Year: "2019",
    Released: "04 Oct 2019",
    Genre: "Crime, Drama, Thriller",
    Director: "Todd Phillips",
    Plot:
      "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
    Language: "English",
    Country: "USA, Canada",
    Awards: "Won 2 Oscars. Another 97 wins & 201 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    imdbRating: "8.5",
    imdbID: "imdb0000013",
    Production: "Warner Bros. Pictures",
  },
  {
    Title: "Life of Pie",
    Year: "2017",
    Released: "N/A",
    Genre: "Drama",
    Director: "N/A",
    Plot:
      "Violet sells perfume and tries kill herself at work. While recuperating at home, she hallucinates 80's rock icons.. She decides to write a metaphysical book about pie and falls in love with a man she is thinks is a demon.",
    Language: "N/A",
    Country: "USA",
    Awards: "N/A",
    Poster: "https://media.s-bol.com/n5Q9PQOQOzvl/550x775.jpg",
    imdbRating: "N/A",
    imdbID: "imdb0000014",
    Production: "N/A",
  },
  {
    Title: "Rangasthalam 1985",
    Year: "2018",
    Released: "29 Mar 2018",
    Genre: "Action, Drama",
    Director: "Sukumar",
    Plot:
      "The fear of his elder brother's death starts to haunt an innocent, hearing impaired guy after they both join forces to overthrow the unlawful 30 year long regime of their village's president.",
    Language: "Telugu",
    Country: "India",
    Awards: "12 wins & 10 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjQ1MjFkN2EtOTU4NS00NDkzLThhNzItODkzYWNjZDMxZjE0XkEyXkFqcGdeQXVyNTgxODY5ODI@._V1_SX300.jpg",
    imdbRating: "8.4",
    imdbID: "imdb0000015",
    Production: "N/A",
  },
  {
    Title: "Dhruva",
    Year: "2016",
    Released: "09 Dec 2016",
    Genre: "Action, Thriller",
    Director: "Surrender Reddy",
    Plot:
      "A committed police officer is on a very dangerous mission to destroy the most corrupt person in the country, Siddharth Abhimanyu.",
    Language: "Telugu, Hindi",
    Country: "India",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNmZhNDMyZDQtNjRmNC00OWRhLWI4OGItNmZlMGRiMzk4YTNjXkEyXkFqcGdeQXVyNjIwNDI3NzI@._V1_SX300.jpg",
    imdbRating: "7.9",
    imdbID: "imdb0000016",
    Production: "N/A",
  },
  {
    Title: "Life",
    Year: "2017",
    Released: "24 Mar 2017",
    Genre: "Horror, Sci-Fi, Thriller",
    Director: "Daniel Espinosa",
    Plot:
      "A team of scientists aboard the International Space Station discover a rapidly evolving life form that caused extinction on Mars and now threatens all life on Earth.",
    Language: "English, Japanese, Vietnamese",
    Country: "UK, USA",
    Awards: "7 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMzAwMmQxNTctYjVmYi00MDdlLWEzMWUtOTE5NTRiNDhhNjI2L2ltYWdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    imdbRating: "6.6",
    imdbID: "imdb0000017",
    Production: "Skydance Films",
  },
  {
    Title: "Black Panther",
    Year: "2018",
    Released: "16 Feb 2018",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Ryan Coogler",
    Plot:
      "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
    Language: "English, Swahili, Nama, Xhosa, Korean",
    Country: "USA",
    Awards: "Won 3 Oscars. Another 109 wins & 265 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg",
    imdbRating: "7.3",
    imdbID: "imdb0000018",
    Production: "Marvel Studios",
  },
  {
    Title: "Black",
    Year: "2005",
    Released: "04 Feb 2005",
    Genre: "Drama",
    Director: "Sanjay Leela Bhansali",
    Plot:
      "The cathartic tale of a young woman who can't see, hear or talk and the teacher who brings a ray of light into her dark world.",
    Language: "Hindi, English",
    Country: "India",
    Awards: "56 wins & 4 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNTI5MmE5M2UtZjIzYS00M2JjLWIwNDItYTY2ZWNiODBmYTBiXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg",
    imdbRating: "8.2",
    imdbID: "imdb0000019",
    Production: "Evokative Films",
  },
  {
    Title: "Race",
    Year: "2016",
    Released: "19 Feb 2016",
    Genre: "Biography, Drama, Sport",
    Director: "Stephen Hopkins",
    Plot:
      "Jesse Owens' quest to become the greatest track and field athlete in history thrusts him onto the world stage of the 1936 Olympics, where he faces off against Adolf Hitler's vision of Aryan supremacy.",
    Language: "English, German",
    Country: "Canada, Germany, France",
    Awards: "6 wins & 8 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTQ3MDM1MDU2NF5BMl5BanBnXkFtZTgwMzM3OTIzNzE@._V1_SX300.jpg",
    imdbRating: "7.1",
    imdbID: "imdb0000020",
    Production: "Focus Features",
  },
];

export const allLanguages = [
  "English",
  "Hindi",
  "Dutch",
  "French",
  "Italian",
  "Spanish",
  "Bulgarian",
  "Mandarian",
  "German",
  "Russian",
  "Japanese",
  "Swedish",
  "Sindarin",
  "Telugu",
  "Other",
];
